export const REQUEST_ADD_TODO = 'REQUEST_ADD_TODO';
export const REQUEST_ADD_JOURNAL_ENTRY = 'REQUEST_ADD_JOURNAL_ENTRY';

export const RECEIVE_TODO = 'RECEIVE_TODO';
export const RECEIVE_JOURNAL_ENTRY = 'RECEIVE_JOURNAL_ENTRY';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';

export const DELETE_TODO = 'DELETE_TODO';
export const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';

