export const REQUEST_ADD_TODO = 'REQUEST_ADD_TODO';
export const REQUEST_ADD_JOURNAL_ENTRY = 'REQUEST_ADD_JOURNAL_ENTRY';
export const REQUEST_JOURNAL_ENTRIES = 'REQUEST_JOURNAL_ENTRIES';

export const RECEIVE_TODO = 'RECEIVE_TODO';
export const RECEIVE_JOURNAL_ENTRY = 'RECEIVE_JOURNAL_ENTRY';
export const RECEIVE_JOURNAL_ENTRIES = 'RECEIVE_JOURNAL_ENTRIES';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';

export const DELETE_TODO = 'DELETE_TODO';
export const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';

export const REQUEST_AUTH_LOGIN = 'REQUEST_AUTH_LOGIN';
export const REQUEST_AUTH_SIGNUP = 'REQUEST_AUTH_SIGNUP';
export const REQUEST_AUTH_LOGOUT = 'REQUEST_AUTH_LOGOUT';
export const RECEIVE_AUTH_USER = 'RECEIVE_AUTH_USER';
export const RECEIVE_AUTH_ERROR = 'RECEIVE_AUTH_ERROR';
export const REMOVE_AUTH_USER = 'REMOVE_AUTH_USER';

export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
