export const REQUEST_AUTH_LOGIN = 'REQUEST_AUTH_LOGIN';
export const REQUEST_AUTH_SIGNUP = 'REQUEST_AUTH_SIGNUP';
export const REQUEST_AUTH_LOGOUT = 'REQUEST_AUTH_LOGOUT';
export const REQUEST_AUTH_STATUS = 'REQUEST_AUTH_STATUS';

export const RECEIVE_AUTH_SUCCESS = 'RECEIVE_AUTH_SUCCESS';
export const RECEIVE_AUTH_ERROR = 'RECEIVE_AUTH_ERROR';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

