export const REQUEST_AUTH_LOGIN = 'REQUEST_AUTH_LOGIN';
export const REQUEST_AUTH_SIGNUP = 'REQUEST_AUTH_SIGNUP';
export const REQUEST_AUTH_LOGOUT = 'REQUEST_AUTH_LOGOUT';

export const RECEIVE_AUTH_USER = 'RECEIVE_AUTH_USER';
export const RECEIVE_AUTH_ERROR = 'RECEIVE_AUTH_ERROR';

