export const REQUEST_ADD_JOURNAL_ENTRY = 'REQUEST_ADD_JOURNAL_ENTRY';
export const REQUEST_UPDATE_JOURNAL_ENTRY = 'REQUEST_UPDATE_JOURNAL_ENTRY';
export const REQUEST_JOURNAL_ENTRIES = 'REQUEST_JOURNAL_ENTRIES';

export const RECEIVE_UPDATED_JOURNAL_ENTRY = 'RECEIVE_UPDATED_JOURNAL_ENTRY';
export const RECEIVE_JOURNAL_ENTRY = 'RECEIVE_JOURNAL_ENTRY';
export const RECEIVE_JOURNAL_ENTRIES = 'RECEIVE_JOURNAL_ENTRIES';

