export const REQUEST_ADD_TODO = 'REQUEST_ADD_TODO';
export const REQUEST_UPDATE_TODO = 'REQUEST_UPDATE_TODO';
export const REQUEST_DELETE_TODO = 'REQUEST_DELETE_TODO';
export const REQUEST_FETCH_TODOS = 'REQUEST_FETCH_TODOS';
export const REQUEST_FETCH_TODOS_BY_TAGS = 'REQUEST_FETCH_TODOS_BY_TAGS';
export const REQUEST_FETCH_TODO = 'REQUEST_FETCH_TODO';
export const REQUEST_TOGGLE_TODO_COMPLETED = 'REQUEST_TOGGLE_TODO_COMPLETED';
export const REQUEST_REMOVE_TAG = 'REQUEST_REMOVE_TAG';
export const REQUEST_ADD_TAG = 'REQUEST_ADD_TAG';

export const RECEIVE_TODO = 'RECEIVE_TODO';
export const SET_ACTIVE_TODO = 'SET_ACTIVE_TODO';
export const RECEIVE_TODOS = 'RECEIVE_TODOS';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_TAG = 'REMOVE_TAG';
export const ADD_TAG = 'ADD_TAG';
export const UPDATE_TODO = 'UPDATE_TODO';
export const SET_TODOS_FILTER = 'SET_TODOS_FILTER';

