export const REQUEST_ADD_TODO = 'REQUEST_ADD_TODO';
export const REQUEST_UPDATE_TODO = 'REQUEST_UPDATE_TODO';
export const REQUEST_DELETE_TODO = 'REQUEST_DELETE_TODO';
export const REQUEST_FETCH_TODOS = 'REQUEST_FETCH_TODOS';

export const RECEIVE_TODO = 'RECEIVE_TODO';
export const RECEIVE_TODOS = 'RECEIVE_TODOS';
export const REMOVE_TODO = 'REMOVE_TODO'; 

